package com.example.bien_aime.wqfinalproject.Servicios;

/**
 * Created by Bien-aime on 11/12/2017.
 */

public class ProveerPaises {

    public static String[] countryStr = {"Seleccionar Pais", "Republica Dominicana", "Estados Unidos", "Haiti"};

    public static String[] states_RepublicaDominicana = {"Seleccionar Ciudad",
            "Santiago de los Caballeros",
            "San Pedro de Macorís",
            "puerto plata",
            "La Romana",
            "San Cristóbal",
            "San Francisco",
            "Boca chica",
            "San pedro de macorix",
            "Boca Chica",
            "Santa Cruz de Barahona",
            "Baní",
            "San Juan de la Maguana",
            "Bonao",
            "Moca",
            "Azua de Compostela",
            "Cotuí",
            "Santa Cruz de El Seibo",
            "Jarabacoa",
            "Nagua",
            "Santa Bárbara de Samaná",
            "Tamboril",
            "Mao Valverde",
            "Esperanza",
            "Pedro Brand",
            "Sosúa",
            "Hato Mayor del Rey",
            "Constanza",
            "Villa Bisonó",
            "Salcedo Hermanas Mirabal",
            "Villa Altagracia",
            "Las Matas de Farfán",
            "Monte Plata",
            "Yamasá",
            "San Ignacio de Sabaneta",
            "San José de Las Matas",
            "San Antonio de Guerra",
            "San José de Ocoa"

    };

    public static String[] states_Haiti = {"Seleccionar Ciudad",
            "Santiago de los Caballeros",
            "San Pedro de Macorís",
            "puerto plata",
            "La Romana",
            "San Cristóbal",
            "San Francisco",
            "Boca chica",
            "San pedro de macorix",
            "Boca Chica",
            "Santa Cruz de Barahona",
            "Baní",
            "San Juan de la Maguana",
            "Bonao",
            "Moca",
            "Azua de Compostela",
            "Cotuí",
            "Santa Cruz de El Seibo",
            "Jarabacoa",
            "Nagua",
            "Santa Bárbara de Samaná",
            "Tamboril",
            "Mao Valverde",
            "Esperanza",
            "Pedro Brand",
            "Sosúa",
            "Hato Mayor del Rey",
            "Constanza",
            "Villa Bisonó",
            "Salcedo Hermanas Mirabal",
            "Villa Altagracia",
            "Las Matas de Farfán",
            "Monte Plata",
            "Yamasá",
            "San Ignacio de Sabaneta",
            "San José de Las Matas",
            "San Antonio de Guerra",
            "San José de Ocoa"
    };


    public static String[] states_EstadosUnidos = {"Seleccionar Ciudad",
            "Santiago de los Caballeros",
            "San Pedro de Macorís",
            "puerto plata",
            "La Romana",
            "San Cristóbal",
            "San Francisco",
            "Boca chica",
            "San pedro de macorix",
            "Boca Chica",
            "Santa Cruz de Barahona",
            "Baní",
            "San Juan de la Maguana",
            "Bonao",
            "Moca",
            "Azua de Compostela",
            "Cotuí",
            "Santa Cruz de El Seibo",
            "Jarabacoa",
            "Nagua",
            "Santa Bárbara de Samaná",
            "Tamboril",
            "Mao Valverde",
            "Esperanza",
            "Pedro Brand",
            "Sosúa",
            "Hato Mayor del Rey",
            "Constanza",
            "Villa Bisonó",
            "Salcedo Hermanas Mirabal",
            "Villa Altagracia",
            "Las Matas de Farfán",
            "Monte Plata",
            "Yamasá",
            "San Ignacio de Sabaneta",
            "San José de Las Matas",
            "San Antonio de Guerra",
            "San José de Ocoa"
    };

}
