package com.example.bien_aime.wqfinalproject.Servicios;

/**
 * Created by Bien-aime on 11/12/2017.
 */

public class ProveerPaises {

    public static String[] countryStr = {"Seleccionar Pais", "Republica Dominicana", "Estados Unidos", "Haiti"};

    public static String[] states_RepublicaDominicana = {"Seleccionar Ciudad",
            "Santiago de los Caballeros",
            "San Pedro de Macorís",
            "puerto plata",
            "La Romana",
            "San Cristóbal",
            "San Francisco",
            "Boca chica",
            "San pedro de macorix",
            "Boca Chica",
            "Santa Cruz de Barahona",
            "Baní",
            "San Juan de la Maguana",
            "Bonao",
            "Moca",
            "Azua de Compostela",
            "Cotuí",
            "Santa Cruz de El Seibo",
            "Jarabacoa",
            "Nagua",
            "Santa Bárbara de Samaná",
            "Tamboril",
            "Mao Valverde",
            "Esperanza",
            "Pedro Brand",
            "Sosúa",
            "Hato Mayor del Rey",
            "Constanza",
            "Villa Bisonó",
            "Salcedo Hermanas Mirabal",
            "Villa Altagracia",
            "Las Matas de Farfán",
            "Monte Plata",
            "Yamasá",
            "San Ignacio de Sabaneta",
            "San José de Las Matas",
            "San Antonio de Guerra",
            "San José de Ocoa"

    };

    public static String[] states_Haiti = {"Seleccionar Ciudad",
            "Santiago de los Caballeros",
            "San Pedro de Macorís",
            "puerto plata",
            "La Romana",
            "San Cristóbal",
            "San Francisco",
            "Boca chica",
            "San pedro de macorix",
            "Boca Chica",
            "Santa Cruz de Barahona",
            "Baní",
            "San Juan de la Maguana",
            "Bonao",
            "Moca",
            "Azua de Compostela",
            "Cotuí",
            "Santa Cruz de El Seibo",
            "Jarabacoa",
            "Nagua",
            "Santa Bárbara de Samaná",
            "Tamboril",
            "Mao Valverde",
            "Esperanza",
            "Pedro Brand",
            "Sosúa",
            "Hato Mayor del Rey",
            "Constanza",
            "Villa Bisonó",
            "Salcedo Hermanas Mirabal",
            "Villa Altagracia",
            "Las Matas de Farfán",
            "Monte Plata",
            "Yamasá",
            "San Ignacio de Sabaneta",
            "San José de Las Matas",
            "San Antonio de Guerra",
            "San José de Ocoa"
    };


    public static String[] sector_Santiago={
            "Seleccionar Sector",
            "Altos de Rafey",
            "Punto Abajo",
            "Altos de Virella",
            "Área Monumental",
            "Arroyo Hondo Abajo",
            "Arroyo Hondo Arriba",
            "Baracoa",
            "Bella Vista",
            "Buena Vista",
            "Buenos Aires",
            "Barrio Lindo (Marilópez)",
            "Barrio Lindo (La Herradura)",
            "Camboya (Marilópez)",
            "Camboya (Los Ciruelitos)",
            "Casco Central",
            "Cerros de Bella Vista",
            "Cerros de Gurabo I",
            "Cerros de Gurabo II",
            "Cerros de Gurabo III",
            "Cerro Hermoso",
            "Cienfuegos",
            "Cristo Rey",
            "Corea",
            "El Dorado I",
            "El Dorado II",
            "Llanos de Gurabo",
            "El Despertar",
            "El Ejido",
            "El Embrujo I",
            "El Embrujo II",
            "El Ensueño",
            "El Embrujo III",
            "El Ingenio",
            "El Ingenio Abajo",
            "El ingenio Arriba",
            "El Invi",
            "El Portal",
            "El Retiro I",
            "El Retiro II",
            "Ensanche Bermúdez",
            "Ensanche Espaillat",
            "Ensanche Francisco Del Rosario Sánchez",
            "Ensanche Julia",
            "Ensanche Libertad",
            "Ensanche Mella I",
            "Ensanche Mella II",
            "Ensanche Pérez",
            "Ensanche Ramos",
            "Ensanche Roman",
            "Ensanche Simón Bolívar",
            "Ensanche Ortega",
            "Gregorio Luperón",
            "Gurabo Abajo",
            "Gurabo al Medio",
            "Gurabo Arriba",
            "Gurabo los Rieles",
            "Hato Mayor"
    };





    public static String[] states_EstadosUnidos = {"Seleccionar Ciudad",
            "Santiago de los Caballeros",
            "San Pedro de Macorís",
            "puerto plata",
            "La Romana",
            "San Cristóbal",
            "San Francisco",
            "Boca chica",
            "San pedro de macorix",
            "Boca Chica",
            "Santa Cruz de Barahona",
            "Baní",
            "San Juan de la Maguana",
            "Bonao",
            "Moca",
            "Azua de Compostela",
            "Cotuí",
            "Santa Cruz de El Seibo",
            "Jarabacoa",
            "Nagua",
            "Santa Bárbara de Samaná",
            "Tamboril",
            "Mao Valverde",
            "Esperanza",
            "Pedro Brand",
            "Sosúa",
            "Hato Mayor del Rey",
            "Constanza",
            "Villa Bisonó",
            "Salcedo Hermanas Mirabal",
            "Villa Altagracia",
            "Las Matas de Farfán",
            "Monte Plata",
            "Yamasá",
            "San Ignacio de Sabaneta",
            "San José de Las Matas",
            "San Antonio de Guerra",
            "San José de Ocoa"
    };

}
